services:
  client:
    image: client:latest
    build:
      context: ./client
      # target: dev
    # environment:
    #   NODE_ENV: prod
    ports:
      - 3000:3000

  usermanagement:
    image: userservice:latest
    build:
      context: ./UserManagement
    ports:
      - 8080:8080
   