services:
  client:
    image: client:latest
    build:
      context: ./client
      # target: dev
    # environment:
    #   NODE_ENV: prod
    ports:
      - 3000:3000

  rabbitmq:
    image: rabbitmq:management
    ports:
     - 5672:5672
     - 15672:15672

  userService:
    image: userservice:latest
    build:
      context: ./UserManagement
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq

  postService:
    image: postservice:latest
    build:
      context: ./PostManagement
    ports:
      - 8090:8080
    depends_on:
      - userService

  statisticService:
    image: statisticservice:latest
    build:
      context: ./StatisticsService
    ports:
      - 8030:8080
    depends_on:
      - userService

  reactionsService:
    image: reactionssservice:latest
    build:
      context: ./ReactionService
    ports:
      - 8040:8080
    depends_on:
      - userService

  journeySservice:
    image: jouurneyservice:latest
    build:
      context: ./JourneyService
    ports:
      - 8020:8080
    depends_on:
      - userService