volumes:
  user_database:
  post_database:

services:
  client:
    image: client:latest
    build:
      context: ./client
      # target: dev
    # environment:
    #   NODE_ENV: prod
    ports:
      - 3000:3000

  rabbitmq:
    image: rabbitmq:management
    ports:
     - 5672:5672
     - 15672:15672

  userservice:
    image: userservice:latest
    build:
      context: ./UserManagement
    ports:
      - 8081:8080
    depends_on:
      - rabbitmq
      - user_database

  postservice:
    image: postservice:latest
    build:
      context: ./PostManagement
    ports:
      - 8082:8080
    depends_on:
      - userservice

  statisticservice:
    image: statisticservice:latest
    build:
      context: ./StatisticsService
    ports:
      - 8083:8080
    depends_on:
      - userservice

  # reactionservice:
  #   image: reactionservice:latest
  #   build:
  #     context: ./ReactionService
  #   ports:
  #     - 8084:8080
  #   depends_on:
  #     - userservice

  journeyservice:
    image: journeyservice:latest
    build:
      context: ./JourneyService
    ports:
      - 8085:8080
    depends_on:
      - userservice
  
  krakend:
    image: devopsfaith/krakend
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    depends_on:
      - userservice
      - postservice
      - journeyservice
      - statisticservice
  
  user_database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    ports:
      - '5433:5432'
    volumes: 
      - ./volumes/user:/data

  post_database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=posts
    ports:
      - '5434:5432'
    volumes: 
      - ./volumes/post:/data

