apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-deployment
  labels:
    app: post-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service       
    spec:
      containers:
        - name: post-service
          image: ghcr.io/aleksandrakrasteva/post-service:dev
          imagePullPolicy: Always
          ports: 
          - containerPort: 8080
          env:
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: global-config
                key: rabbitmq-host
          - name: RABBITMQ_PORT
            valueFrom:
              configMapKeyRef:
                  name: global-config
                  key: rabbitmq-port
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                  name: global-secret
                  key: rabbitmq-user 
          - name: RABBITMQ_PASS
            valueFrom:
              secretKeyRef:
                name: global-secret
                key: rabbitmq-pass
          - name: POST_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: global-config
                key:  post-db-host   
          - name: POST_DB_PORT
            valueFrom:
              configMapKeyRef:
                name: global-config
                key:  post-db-port   
          - name: POST_DB_USER
            valueFrom:
              secretKeyRef:
                name: global-secret
                key: post-db-user
          - name: POST_DB_PASS
            valueFrom:
              secretKeyRef:
                name: global-secret
                key: post-db-pass
#           securityContext:
#             allowPrivilegeEscalation: false
#             runAsNonRoot: true
#             readOnlyRootFilesystem: true
#             runAsUser: 1000
#             capabilities:
#               drop: 
#                 - ALL
#           resources:
#             limits:
#               cpu: 3040m
#               memory: "1000M"
#             requests:
#               cpu: 3040m
#               memory: "1000M"
---
apiVersion: v1
kind: Service
metadata:
  name: post-service-service
spec:
  selector:
    app: post-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080