apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-config
data:
  post-db-host: "post-database.postgres.database.azure.com"
  post-db-port: "5432"
  post-db-database: "postgres"
  rabbitmq-host: "rabbitmq-service"
  rabbitmq-port: "5672"
