apiVersion: apps/v1
kind: Deployment
metadata:
  name: journey-service-deployment
  labels:
    app: journey-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: journey-service
  template:
    metadata:
      labels:
        app: journey-service       
    spec:
      containers:
        - name: journey-service
          image: ghcr.io/aleksandrakrasteva/journey-service:main
          imagePullPolicy: Always
          ports: 
          - containerPort: 8080
          env:
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: azure-config
                key: rabbitmq-host
          - name: RABBITMQ_PORT
            valueFrom:
              configMapKeyRef:
                  name: azure-config
                  key: rabbitmq-port
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                  name: azure-secret
                  key: rabbitmq-user 
          - name: RABBITMQ_PASS
            valueFrom:
              secretKeyRef:
                name: azure-secret
                key: rabbitmq-pass
          - name: JOURNEY_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: azure-config
                key:  journey-db-host   
          - name: JOURNEY_DB_PORT
            valueFrom:
              configMapKeyRef:
                name: azure-config
                key:  journey-db-port  
          - name: JOURNEY_DB_NAME
            valueFrom:
              secretKeyRef:
                name: azure-config
                key: journey-db-name
          - name: JOURNEY_DB_PASS
            valueFrom:
              secretKeyRef:
                name: azure-secret
                key: journey-db-pass
---
apiVersion: v1
kind: Service
metadata:
  name: journey-service-service
spec:
  selector:
    app: journey-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080