apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  user-db-host: "user-db-service"
  user-db-port: "5432"
  user-db-database: "users"
  post-db-host: "post-db-service"
  post-db-port: "5432"
  post-db-database: "posts"
  rabbitmq-host: "rabbitmq-service"
  rabbitmq-port: "5672"
