apiVersion: v1
kind: PersistentVolume
metadata:
  name: journey-db-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/journey/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: journey-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage