name: CD Pipeline

on:
 push:
    branches:
      - dev
  # workflow_run:
  #   workflows: ["CI Pipeline"]
  #   types:
  #     - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if repository is checked out
      id: check-repo
      shell: pwsh
      run: |
        if (Test-Path -Path "${{ secrets.REPO_PATH }}") {
          echo "repo-exists=true" >> $env:GITHUB_ENV
        } else {
          echo "repo-exists=false" >> $env:GITHUB_ENV
        }

    - name: Checkout repository if not present
      if: env.repo-exists == 'false'
      shell: pwsh
      run: |
        git clone https://github.com/AleksandraKrasteva/skipass.git ${{ secrets.REPO_PATH }}

    - name: Switch to dev branch and pull latest change
      shell: pwsh
      run: |
        Set-Location -Path ${{ secrets.REPO_PATH }}
        git checkout dev
        git pull origin dev


    # - name: Set up kubectl
    #   run: |
    #     curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    #     chmod +x ./kubectl
    #     sudo mv ./kubectl /usr/local/bin/kubectl

    # - name: Configure kubeconfig
    #   env:
    #     KUBECONFIG: ${{ secrets.KUBECONFIG }}
    #   run: |
    #     echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Check Deployment Status
      id: check-deployment
      run: |
        kubectl get deployment post-service -o jsonpath='{.status.readyReplicas}' || echo "0"
      continue-on-error: true

    - name: Deploy Application if Not Running
      if: steps.check-deployment.outputs.status == '0'
      run: |
        kubectl apply -f ${{ secrets.REPO_PATH }}/post-service.yaml

    - name: Update Deployment 
      run: |
        kubectl set image deployment/post-service post-service=ghcr.io/${{ github.repository_owner }}/post-service:dev
        kubectl rollout status deployment/post-service
